---
apiVersion: v1 
kind: Namespace
metadata: 
  name: dovns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy 
  namespace: dovns
  labels: 
    app: dov 
    name: dov-deploy 
spec: 
  replicas: 4
  selector:
    matchLabels:
      app: dov 
      name: dov-po
  template:
    metadata:
      name: dov-po
      namespace: dovns
      labels:
        app: dov 
        name: dov-po
    spec:
      containers:
      - name: dov-container 
        image: chukmunnlee/cfdsa-dov-bear:v1.1
        imagePullPolicy: IfNotPresent
        env:
        - name: INSTANCE_NAME
          value: my-first-deployment
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
        resources: 
          limits:
            cpu: 20m
            memory: 50Mi
--- 
apiVersion: v1 
kind: Service
metadata:
  name: dov-svc
  namespace: dovns 
  labels: 
    app: dov 
    name: dov-svc
spec:
  selector:
    app: dov 
    name: dov-po
  ports:
  - name: dov-svc-port
    port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dov-bear-ing
  namespace: dovns
  labels:
    app: dov
    name: dov-bear-ing
spec:
  ingressClassName: nginx
  rules:
    - host: dov-bear.104.248.98.107.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dov-svc
                port:
                  name: dov-svc-port
