apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      env: development
    includeSelectors: true
    includeTemplates: true

namePrefix: dev-
namespace: devns

replicas:
  - name: dov-deploy
    count: 1


images:
  - name: chukmunnlee/cfdsa-dov-bear
    newName: chukmunnlee/dov-bear
    newTag: v5

configMapGenerator:
  - name: dov-cm
    namespace: devns
    behavior: create
    literals:
      - NAME=fred

secretGenerator:
  - name: dov-secret
    namespace: devns
    behavior: create
    literals:
      - NAME=fred
  
patches:
  - path: patches.yaml
    target:
      group: apps/v1
      kind: Deployment
      name: dov-deploy
  - path: delete-ingress.yaml


replacements:
  - source:
      kind: Service
      name: dov-svc
      fieldPath: metadata.name
    targets:
      - select: # select the resource
          kind: Deployment
          name: dov-deploy
        fieldPaths:
          - spec.template.spec.containers.[name=dov-container].env.[name=SERVICE_NAME].value
