---
apiVersion: v1
kind: Namespace
metadata:
  name: api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-v2-deploy
  namespace: api
  labels:
    app: api
    name: api-deploy

spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
      name: api-po
      version: v2
  template:
    metadata:
      name: api-po
      labels:
        app: api
        name: api-po
        version: v2
    spec:
      containers:
        - name: api-container
          image: chukmunnlee/fake-api:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: api-v2-svc
  namespace: api
  labels:
    app: api
    name: api-v2-svc
spec:
  type: ClusterIP
  selector:
    app: api
    name: api-po
    version: v2
  ports:
    - port: 3000
      targetPort: 3000
