---
apiVersion: v1
kind: Namespace
metadata:
  name: myns
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlc-pvc
  namespace: myns
  labels:
    app: mysql
    name: mysqlc-pvc
spec:
  storageClassName: do-block-storage
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  namespace: myns
  labels:
    app: mysql
    name: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      name: mysql-po

  template:
    metadata:
      name: mysql-po
      labels:
        app: mysql
        name: mysql-po
    spec:
      volumes:
        - name: data-vol
          persistentVolumeClaim:
            claimName: mysqlc-pvc
      containers:
        - name: mysql-container
          image: mysql:8
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: changeit
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data-vol
              mountPath: /var/lib/mysqlm
