---
apiVersion: v1
kind: Pod
metadata:
  name: dov-po
  namespace: myns
  labels:
    app: dov
    name: dov-po
spec:
  containers:
    - name: dov-container
      image: chukmunnlee/dov-bear:v5
      imagePullPolicy: IfNotPresent
      env:
        - name: INSTANCE_NAME
          value: my-first-pod
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      ports:
        - containerPort: 3000
