---
apiVersion: v1
kind: Pod
metadata:
  name: fortune-pod
  namespace: myns
  labels:
    app: fortune
    name: fortune-pod
spec:
  containers:
    - name: fortune-container
      image: chukmunnlee/cfdsa-dov-bear:v1.1
      imagePullPolicy: IfNotPresent
      env:
        - name: INSTANCE_NAME
          value: my-first-pod
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      ports:
        - containerPort: 3000
      livenessProbe:
        httpGet:
          path: /healthz
          port: 3000
