---
apiVersion: v1
kind: Namespace
metadata:
  name: minions
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm
  namespace: minions
  labels: 
    app: minio
    name: minio-cm
data:
  MINIO_ROOT_USER: root
  MINIO_CI_CD: "1"
  MINIO_DATA_DIR: /bitnami/minio/data
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minions
  labels:
    app: minio
    name: minio-secret
type: Opaque
data:
  MINIO_ROOT_PASSWORD: Y2hhbmdlaXQ=


